### ISSUE TITLE
Greg's ToDo list

### ISSUE THREAD

**Issue by gkiar** [openconnectome/SIMPLEX#12]
- [x] start making Phase I report (due in 2 weeks)
- [x] update homepage to have link to Phase I report and the CS slides
- [x] make sure each ref in the CS page that is in 2015 is in the report

**Comment by jovo** [comment]
### q2 report details:

literally copy old stuff
then replace all old figure panels with newer ones if they exist
and make sure each figure is in its own <div> and fits on page
we need to add disa’s recent kmeans submission and kunals ndblaze to references in slides (and then also in report)
and lets add a new section in references called “in preparation"
in it, add:
1. LOL
2. MGC
3. Reliability
4. ndmg
5. ndpaper

also, let's add links to each relevant repo in the "code" section

**Comment by gkiar** [comment]
covered in #13
