### ISSUE TITLE
ToDo for Tues, July 5

### ISSUE THREAD

**Issue by gkiar** [openconnectome/SIMPLEX#13]
Fix the reporting doc:

**general**:
- [x] learn when simplex started

> May 2015
- [x] title should be "Simplex Phase I Report"
- [x] add link on landing page to point to the report

**references**:
- [x] update refs table to contain all papers after simplex start date 
- [x] presentations (from jovo cv + Da has things)
- [x] conference posters

**content**:
- [x] update figures from neurodata paper
- [x] clarity data analysis repo has content/a classification result. add it
- [x] for datification, update tables from neurodata paper
- [x] for datafication, add mri datatable for all processed
- [x] discovery, add synapse stuff
- [x] discovery, add mgc real data section
- [x] datification should just be tables, tasically

**Comment by jovo** [comment]
:ok_hand:

On Fri, Jul 1, 2016 at 12:29 PM, Greg Kiar notifications@github.com wrote:

> Fix the reporting doc:
> 
> _general_:
> - learn when simplex started (sept 2015?)
> - title should be "Simplex Phase I Report"
> - add link on landing page to point to the report
> 
> _references_:
> - update refs table to contain all papers after simplex start date
> - presentations (from jovo cv + Da has things)
> - conference posters
> 
> _content_:
> - update figures from neurodata paper
> - clarity data analysis repo has content/a classification result. add
>   it
> - for datification, update tables from neurodata paper
> - for datafication, add mri datatable for all processed
> - discovery, add synapse stuff
> - discovery, add mgc real data section
> - datification should just be tables, tasically
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/SIMPLEX/issues/13, or mute the thread
> https://github.com/notifications/unsubscribe/AACjcsmPwjy4W0QUQVyugOlLmCw1wZYxks5qRUBigaJpZM4JDS0r
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
- [x] remove SSDBM
- [x] update ndblaze
- [x] separate pubs and pre-prints
- [x] report which acknowledge SIMPLEX

**Comment by gkiar** [comment]
Report: https://github.com/neurodata/SIMPLEX/blob/gh-pages/Reporting/reports/papers_acknowledging_simplex.md
